gps_retry_limit: 3
logs_path: C:\Users\Ueno\Downloads\tmp\logs
max_logs: 100
renumber_all: true
sorted_path: C:\Users\Ueno\Downloads\tmp\Sorted
unsorted_path: C:\Users\Ueno\Downloads\tmp\Unsorted
user_agent: APO-eo1csue8s2
wait_time: 80
wait_time_minutes: 2
